version: '3'
services:
  app:
    build: .
    restart: always
    image: spring_boot_pro:latest   # My spring project Docker image
    ports:
      - "9090:9090"
    environment:
      MYSQL_HOST: db
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: db # Database container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: docker_pro
    ports:
      - "3307:3306"
    volumes:
      - appu:/var/lib/mysql

volumes:
  appu:  # Volume created to persist data in this volume
